### ISSUE TITLE
face alignment problem

### ISSUE THREAD

**Issue by xieyipeng** [yinguobing/Playground#1]
* 你好，我在你的[博客](https://yinguobing.com/)中看到[这篇文章](https://yinguobing.com/face-alignment/)

* 文中您裁剪图像的最终结果是192*192

* 所以有个问题想要请教：

* 如果我想裁剪的图像大小是512*512，我该如何设置变换后的五官坐标：key_marks？

**Comment by yinguobing** [comment]
可以这样做：
1. 定义一个归一化的坐标空间，长、宽为1。
2. 定位五官坐标，它们在此空间中取值范围为 0~1。
3. 用你需要裁剪的实际尺寸乘以归一化后的坐标，得到真实像素位置。

注意变换后的五官位置完全是由你自己来指定的，一般是根据实际业务来确定。

**Comment by xieyipeng** [comment]
* 在第二步中，如何定位五官坐标呢？

* 我现在是这样做的：

* 先在PS中新建`192*192`的画布，再标记上您原有博客中的关键点，保存图片，然后新建一张`512*512`的画布，等比缩放之前的`192*192`的画布，使其完全贴合，这样得到256*256像素下的五官坐标

* 这样做可行吗？

**Comment by yinguobing** [comment]
可以的。

**Comment by xieyipeng** [comment]
好的，非常感谢！
